from sqlalchemy.orm import Session
from src.models.animal import Animal

DEFAULT_CATALOG_ANIMALS = [
    {
        "code": "hippopotamus",
        "name": "Hippopotamus",
        "scientific_name": "Choeropsis liberiensis",
        "category": "Zoo",
        "default_image_url": "https://static.bangkokpost.com/media/content/20240913/c1_2865088.jpg",
        "default_story": "A delightfully bouncy pygmy hippo who loves water baths and crunchy cabbage.",
        "default_fav_food": "Golden Berries & Cabbage",
        "default_temperament": "Extremely Playful",
        "catalog_order": 1,
    },
    {
        "code": "badger",
        "name": "Badger",
        "scientific_name": "Meles meles",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1579613832125-5d34a13ffe0a?w=800&auto=format&fit=crop",
        "default_story": "A tenacious digger with distinctive black-and-white face stripes.",
        "default_fav_food": "Earthworms & Roots",
        "default_temperament": "Curious & Bold",
        "catalog_order": 2,
    },
    {
        "code": "red_fox",
        "name": "Red Fox",
        "scientific_name": "Vulpes vulpes",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1516934024742-b461fba47600?w=800&auto=format&fit=crop",
        "default_story": "Clever woodland wanderer with a fluffy rust-colored tail.",
        "default_fav_food": "Forest Berries & Insects",
        "default_temperament": "Cunning & Observant",
        "catalog_order": 3,
    },
    {
        "code": "monkey",
        "name": "Monkey",
        "scientific_name": "Macaca fascicularis",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&auto=format&fit=crop",
        "default_story": "A quick-witted climber always searching for tasty fruit snacks.",
        "default_fav_food": "Ripe Bananas & Figs",
        "default_temperament": "Mischievous",
        "catalog_order": 4,
    },
    {
        "code": "elephant",
        "name": "Asian Elephant",
        "scientific_name": "Elephas maximus",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=800&auto=format&fit=crop",
        "default_story": "Gentle giant with immense memory and deep social bonds.",
        "default_fav_food": "Sugar Cane & Grasses",
        "default_temperament": "Gentle & Wise",
        "catalog_order": 5,
    },
    {
        "code": "capybara",
        "name": "Capybara",
        "scientific_name": "Hydrochoerus hydrochaeris",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=800&auto=format&fit=crop",
        "default_story": "The friend of all creatures, master of relaxation by the riverside.",
        "default_fav_food": "Water Plants & Melons",
        "default_temperament": "Ultimate Zen",
        "catalog_order": 6,
    },
    {
        "code": "sea_otter",
        "name": "Sea Otter",
        "scientific_name": "Enhydra lutris",
        "category": "Marine",
        "default_image_url": "https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=800&auto=format&fit=crop",
        "default_story": "Floats on its back and cracks sea shells using favorite rocks.",
        "default_fav_food": "Clams & Crabs",
        "default_temperament": "Playful & Social",
        "catalog_order": 7,
    },
    {
        "code": "emperor_penguin",
        "name": "Emperor Penguin",
        "scientific_name": "Aptenodytes forsteri",
        "category": "Polar",
        "default_image_url": "https://images.unsplash.com/photo-1598439210625-5067c578f3f6?w=800&auto=format&fit=crop",
        "default_story": "Endures freezing polar blizzards with synchronized group huddles.",
        "default_fav_food": "Krill & Silverfish",
        "default_temperament": "Resilient & Dignified",
        "catalog_order": 8,
    },
    {
        "code": "red_panda",
        "name": "Red Panda",
        "scientific_name": "Ailurus fulgens",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop",
        "default_story": "Tree-dwelling acrobat with a striped ring tail and white whisker tufts.",
        "default_fav_food": "Tender Bamboo Shoots",
        "default_temperament": "Shy & Sweet",
        "catalog_order": 9,
    },
    {
        "code": "koala",
        "name": "Koala",
        "scientific_name": "Phascolarctos cinereus",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1579380656108-3286649ff5c9?w=800&auto=format&fit=crop",
        "default_story": "Spends up to 20 hours a day napping in eucalyptus tree branches.",
        "default_fav_food": "Fresh Eucalyptus Leaves",
        "default_temperament": "Sleepy & Calm",
        "catalog_order": 10,
    },
    {
        "code": "giant_panda",
        "name": "Giant Panda",
        "scientific_name": "Ailuropoda melanoleuca",
        "category": "Zoo",
        "default_image_url": "https://images.unsplash.com/photo-1527118732049-c88155f2107c?w=800&auto=format&fit=crop",
        "default_story": "Beloved black-and-white bear that loves somersaults down grassy hills.",
        "default_fav_food": "Crisp Bamboo Stems",
        "default_temperament": "Goofy & Peaceful",
        "catalog_order": 11,
    },
    {
        "code": "fennec_fox",
        "name": "Fennec Fox",
        "scientific_name": "Vulpes zerda",
        "category": "Desert",
        "default_image_url": "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?w=800&auto=format&fit=crop",
        "default_story": "Small desert fox equipped with huge ears to dissipate heat and detect insects.",
        "default_fav_food": "Locusts & Lizards",
        "default_temperament": "Energetic & Alert",
        "catalog_order": 12,
    },
    {
        "code": "bengal_tiger",
        "name": "Bengal Tiger",
        "scientific_name": "Panthera tigris tigris",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800&auto=format&fit=crop",
        "default_story": "Majestic apex predator with bold amber eyes and silent paws.",
        "default_fav_food": "Wild Boar & Deer",
        "default_temperament": "Fierce & Noble",
        "catalog_order": 13,
    },
    {
        "code": "african_lion",
        "name": "African Lion",
        "scientific_name": "Panthera leo",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&auto=format&fit=crop",
        "default_story": "The king of the savanna basking under golden acacia trees.",
        "default_fav_food": "Savanna Game",
        "default_temperament": "Regal & Protective",
        "catalog_order": 14,
    },
    {
        "code": "meerkat",
        "name": "Meerkat",
        "scientific_name": "Suricata suricatta",
        "category": "Desert",
        "default_image_url": "https://images.unsplash.com/photo-1550974482-19e0787fa632?w=800&auto=format&fit=crop",
        "default_story": "Stands tall on hind legs on sentry duty watching the horizon.",
        "default_fav_food": "Scorpions & Spiders",
        "default_temperament": "Vigilant & Cooperative",
        "catalog_order": 15,
    },
    {
        "code": "sloth",
        "name": "Three-Toed Sloth",
        "scientific_name": "Bradypus tridactylus",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop",
        "default_story": "Moves at its own serene pace in the high rainforest canopy.",
        "default_fav_food": "Cecropia Tree Leaves",
        "default_temperament": "Easygoing & Slow",
        "catalog_order": 16,
    },
    {
        "code": "alpaca",
        "name": "Alpaca",
        "scientific_name": "Vicugna pacos",
        "category": "Domestic",
        "default_image_url": "https://images.unsplash.com/photo-1519066629447-267fffa62d4b?w=800&auto=format&fit=crop",
        "default_story": "Fluffy highland companion with soft wool and cheerful curiosity.",
        "default_fav_food": "Sweet Mountain Hay",
        "default_temperament": "Inquisitive & Gentle",
        "catalog_order": 17,
    },
    {
        "code": "raccoon",
        "name": "Raccoon",
        "scientific_name": "Procyon lotor",
        "category": "Wild",
        "default_image_url": "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&auto=format&fit=crop",
        "default_story": "Clever masked adventurer with dexterous front paws for solving puzzles.",
        "default_fav_food": "Shiny Fruits & Nuts",
        "default_temperament": "Inquisitive & Clever",
        "catalog_order": 18,
    },
]


def seed_catalog_animals(db: Session):
    """Seed the 18 master catalog animals if table is empty."""
    existing_count = db.query(Animal).count()
    if existing_count > 0:
        print(f"[Seeds] Animal catalog already seeded ({existing_count} records).")
        return

    print("[Seeds] Seeding 18 master catalog animals into database...")
    for item in DEFAULT_CATALOG_ANIMALS:
        animal = Animal(
            code=item["code"],
            name=item["name"],
            scientific_name=item["scientific_name"],
            category=item["category"],
            default_image_url=item["default_image_url"],
            default_story=item["default_story"],
            default_fav_food=item["default_fav_food"],
            default_temperament=item["default_temperament"],
            catalog_order=item["catalog_order"],
        )
        db.add(animal)

    db.commit()
    print("[Seeds] Successfully seeded master animal catalog.")

